### ISSUE TITLE
Link to the guide on template creation in the README is broken

### ISSUE THREAD

**Issue by dpurge** [dwqs/chare#2]
In the readme there is a broken link to the guide on template creation: https://github.com/dwqs/template-simple/blob/master/README_en.md

**Comment by dwqs** [comment]
This repo is deleted, you can learn about writing template [here](https://github.com/dwqs/blog/issues/56) or [writing custom templates](https://github.com/vuejs/vue-cli#writing-custom-templates-from-scratch). And I have updated the readme. I'm sorry for that.
